-- SevaMitra — Operations analytics schema
-- SQLite-compatible schema for the simulated operations dataset.
-- Tables mirror the CSV files generated by generate_operations.py:
--   doctors.csv, appointments.csv, pharmacy_stock.csv

-- Doctor roster: one doctor per specialty with a daily consultation capacity.
CREATE TABLE doctors (
    doctor_id        TEXT PRIMARY KEY,
    specialty        TEXT NOT NULL,
    capacity_per_day INTEGER NOT NULL
);

-- Appointments: every scheduled consultation, including ones that were
-- cancelled or marked as no-show. "completed" rows drive the consultation KPIs.
CREATE TABLE appointments (
    appointment_id           TEXT PRIMARY KEY,
    doctor_id                TEXT NOT NULL REFERENCES doctors(doctor_id),
    specialty                TEXT NOT NULL,
    village                  TEXT NOT NULL,
    language                 TEXT NOT NULL CHECK (language IN ('en', 'hi', 'pa')),
    patient_age              INTEGER NOT NULL,
    age_group                TEXT NOT NULL,
    scheduled_time           TEXT NOT NULL,   -- ISO "YYYY-MM-DD HH:MM:SS"
    outcome                  TEXT NOT NULL CHECK (outcome IN ('completed', 'cancelled', 'no_show')),
    wait_min                 INTEGER NOT NULL,
    symptom                  TEXT NOT NULL,
    urgency                  TEXT NOT NULL CHECK (urgency IN ('emergency', 'high', 'routine')),
    duration_min             INTEGER NOT NULL,
    connectivity             TEXT NOT NULL CHECK (connectivity IN ('good', 'fair', 'poor')),
    media_type               TEXT,            -- NULL when not completed
    prescription_issued      INTEGER NOT NULL, -- 0/1
    medicine_prescribed      TEXT,
    pharmacy_stock_shortage  INTEGER NOT NULL, -- 0/1
    follow_up_required       INTEGER NOT NULL, -- 0/1
    rating                   INTEGER NOT NULL, -- 0 when not completed
    date                     TEXT NOT NULL,    -- scheduled_time as date (YYYY-MM-DD)
    hour                     INTEGER NOT NULL,
    weekday                  TEXT NOT NULL,
    is_rural                 INTEGER NOT NULL, -- 1 if village is outside hub towns
    is_specialist            INTEGER NOT NULL  -- 1 if specialty != general
);

-- Pharmacy stock checks: per pharmacy x medicine x specialty, how often the
-- medicine was found out of stock across routine checks.
CREATE TABLE pharmacy_stock (
    id                 INTEGER PRIMARY KEY AUTOINCREMENT,
    pharmacy           TEXT NOT NULL,
    specialty          TEXT NOT NULL,
    medicine           TEXT NOT NULL,
    stock_checks       INTEGER NOT NULL,
    stock_shortages    INTEGER NOT NULL,
    availability_rate  REAL NOT NULL
);
